# Application
spring.application.name=freelancehub
server.port=8080
server.servlet.context-path=/freelance

# DataSource MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/freelancehub
spring.datasource.username=root
spring.datasource.password=