# Application
spring.application.name=freelancehub
server.port=8080
server.servlet.context-path=/freelance

# DataSource MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/freelancehub
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# SQL init (pour data.sql)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always